WebApplication1/WebApplication1/Models/Agent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Agent
    {
        public  int id { get; set; }
        public string Name { get; set; }
        public  long mob { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/AgentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AgentController : Controller
    {
        IAgentDAL agentDAL;

        public AgentController(AgentDAL agentDAL)
        {
            this.agentDAL = agentDAL;
        }

        // GET: Agent
        public ActionResult Index()
        {
            ViewData["subTitle"] = "Agent List";
            ViewData["status"]=TempData["status"];
            var agents= agentDAL.GetAllAgents();
            return View(agents);
        }

        // GET: Agent/Details/5
        public ActionResult Details(int id)
        {
            var agents= agentDAL.GetAgentDetails(id);
            return View(agents);
        }

        // GET: Agent/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Agent/Create
        [HttpPost]
        public ActionResult Create(Agent agent)
        {
            try
            {
                // TODO: Add insert logic here
                int i = agentDAL.agentInsert(agent);
                if(i == 1)
                {
                   TempData["status"] = "Data inserted Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["status"] = "Data Not Inserted";
                    return RedirectToAction("Index");
                }
                
            }
            catch
            {
                TempData["status"] = "Data Not Inserted";
                return RedirectToAction("Index");
            }
        }

        // GET: Agent/Edit/5
        public ActionResult Edit(int id)
        {
            var agents = agentDAL.GetAgentDetails(id);
            return View(agents);
        }

        // POST: Agent/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Agent agent)
        {
            try
            {
                // TODO: Add update logic here
                int i = agentDAL.agentUpdate(agent);
                if (i == 1)
                {
                    TempData["status"] = "Data Updated Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["status"] = "Data Not Updated";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                TempData["status"] = "Data Not Updated";
                return RedirectToAction("Index");
            }
        }

        // GET: Agent/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                int i = agentDAL.agentDelete(id);
                if (i == 1)
                {
                    TempData["status"] = "Data Deleted Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["status"] = "Data Not Deleted";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                TempData["status"] = "Data Not Deleted";
                return RedirectToAction("Index");
            }
        }

        // POST: Agent/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            
            try
            {
                // TODO: Add delete logic here
                int i = agentDAL.agentDelete(id);
                if (i == 1)
                {
                    TempData["status"] = "Data Deleted Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["status"] = "Data Not Deleted";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                TempData["status"] = "Data Not Deleted";
                return RedirectToAction("Index");
            }
        }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Agent/Create.cshtml
@model WebApplication1.Models.Agent

@{
    ViewBag.Title = "Create";
}

<h2>Add Agent</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"  />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/Agent/Details.cshtml
@model WebApplication1.Models.Agent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mob)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/WebApplication1/Views/Agent/Edit.cshtml
@model WebApplication1.Models.Agent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/Agent/Index.cshtml
@model List<WebApplication1.Models.Agent>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewData["subTitle"]</h2>

<h3>@ViewData["status"]</h3>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Agent Name
        </th>
        <th>
            Agent Contact No.
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.mob)
        </td>
        <td>
       
            @Html.ActionLink("Edit", "Edit", "Agent", new { id=item.id },null) |
            @Html.ActionLink("Details", "Details", "Agent", new { id=item.id }, null) |
            @Html.ActionLink("Delete", "Delete", "Agent", new { id=item.id }, FormMethod.Post)
        </td>
    </tr>
}

</table>

WebApplication1/WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebApplication1/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>